name: VitalPlayerTime
version: @version@
main: com.tamrielnetwork.vitalplayertime.VitalPlayerTime
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to open a crafting interface.
commands:
  ptime:
    description: "Main command"
    usage: "/ptime"
permissions:
  vitalplayertime.set:
    description: "Permission to change playertime"
    default: op